In [1]:
import os as os
import glob
import json
import pandas as pd

In [5]:
totalContents = []
json_dir_name = '/Users/priyankaraju/Documents/Jupyter Notebooks/Sept2020/true-news/'

In [6]:
for file_name in [file for file in os.listdir(json_dir_name) if file.endswith('.json')]:
  with open(json_dir_name + file_name) as json_file:
    data = json.load(json_file)
    totalContents.append(data)

In [7]:
print(len(totalContents))

37213

In [8]:
df = pd.DataFrame(totalContents)

In [9]:
df.head()

,created_at,id,id_str,text,truncated,entities,source,in_reply_to_status_id,in_reply_to_status_id_str,in_reply_to_user_id,...,retweet_count,favorite_count,favorited,retweeted,possibly_sensitive,lang,extended_entities,quoted_status_id,quoted_status_id_str,quoted_status
0,Sun Jul 22 16:31:58 +0000 2018,1021070359322296325,1021070359322296325,Briefing skipper à la Trinité sur Mer pour la ...,True,"{'hashtags': [], 'symbols': [], 'user_mentions...","<a href=""http://twitter.com/download/iphone"" r...",NaN,None,NaN,...,2,4,False,False,False,fr,NaN,NaN,NaN,NaN
1,Sun Jul 22 08:22:51 +0000 2018,1020947266809532416,1020947266809532416,Top story: A Minister Feting a Lynch Mob? Indi...,False,"{'hashtags': [], 'symbols': [], 'user_mentions...","<a href=""https://www.tweetedtimes.com"" rel=""no...",NaN,None,NaN,...,0,0,False,False,False,en,NaN,NaN,NaN,NaN
2,Tue Nov 20 17:46:08 +0000 2018,1064937953259110401,1064937953259110401,BREAKING: Jim Acosta loses title of ‘Biggest T...,False,"{'hashtags': [], 'symbols': [], 'user_mentions...","<a href=""http://twitter.com"" rel=""nofollow"">Tw...",NaN,None,NaN,...,0,0,False,False,False,en,NaN,NaN,NaN,NaN
3,Sun Mar 13 19:07:38 +0000 2016,709093581965959168,709093581965959168,#TRUTH @ Apostolic Church of God - Chicago htt...,False,"{'hashtags': [{'text': 'TRUTH', 'indices': [0,...","<a href=""http://instagram.com"" rel=""nofollow"">...",NaN,None,NaN,...,0,0,False,False,False,en,NaN,NaN,NaN,NaN
4,Sat Nov 10 14:05:05 +0000 2018,1061258447721775105,1061258447721775105,#BREAKING It seems this is not the first time ...,True,"{'hashtags': [{'text': 'BREAKING', 'indices': ...","<a href=""https://www.hootsuite.com"" rel=""nofol...",NaN,None,NaN,...,0,0,False,False,False,en,NaN,NaN,NaN,NaN

In [10]:
df.to_csv('finalRealTweets.csv', index=False)